const express = require('express');
const fs = require('fs');
const path = require('path');
const app = express();
const PORT = process.env.PORT || 10000;
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || 'CHANGE-ME-BEFORE-LAUNCH';
const DATA = path.join(__dirname, 'data.json');
app.use(express.json({limit:'5mb'}));
app.use(express.urlencoded({extended:true,limit:'5mb'}));
function load(){try{return JSON.parse(fs.readFileSync(DATA,'utf8'))}catch{return {jobs:[],pros:[],tickets:[]}}}
function save(d){fs.writeFileSync(DATA,JSON.stringify(d,null,2))}
function id(){return 'SBD-'+new Date().getFullYear()+'-'+String(Math.floor(Math.random()*99999)).padStart(5,'0')}
const pros=[
{name:'Boateng Gabriel',area:'Lapaz',services:'New construction wiring, lighting installation, breaker panel upgrades, repairs, rewiring'},
{name:'Appiah Daniel',area:'Weija',services:'CCTV, electric fence, general wiring, gate automation'},
{name:'Mensah Isaac',area:'Nungua',services:'Commercial & industrial, new buildings, power protection systems'},
{name:'Shaibu Issah',area:'Kasoa',services:'Generator installation and repairs, heavy-duty installation'},
{name:'Kotochie Simpson',area:'Nungua',services:'Gate automation, CCTV, fire alarms, access control'}];
function page(body,title='Services by Dela'){return `<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>${css}</style></head><body><header><a class="brand" href="/">⌂ <span>SERVICES <b>BY DELA</b></span></a><nav><a href="/">Home</a><a href="/book">Book</a><a href="/track">Track</a><a href="/support">Support</a><a href="/pro">Become a Pro</a></nav></header>${body}<footer><b>Services by Dela</b><br>Book the right professional for the job.<br>📞 <a href="tel:0541721528">0541721528</a> · 💬 <a href="https://wa.me/233541721528">WhatsApp</a></footer></body></html>`}
const css=`*{box-sizing:border-box}body{margin:0;font-family:Inter,Arial,sans-serif;color:#10284a;background:#f7f9fc}header{height:72px;background:#0d2b52;color:#fff;display:flex;align-items:center;justify-content:space-between;padding:0 6%;position:sticky;top:0;z-index:5}.brand{color:#fff;text-decoration:none;font-weight:900;font-size:20px;display:flex;gap:8px;align-items:center}.brand b{color:#ffc62b}nav{display:flex;gap:20px}nav a{color:#fff;text-decoration:none}.hero{padding:70px 7%;display:grid;grid-template-columns:1.05fr .95fr;gap:35px;align-items:center;background:linear-gradient(120deg,#fff 0%,#eef4fb 100%)}h1{font-size:clamp(40px,6vw,68px);line-height:1;margin:0 0 20px}.gold{color:#f5b900}.lead{font-size:20px;line-height:1.6;color:#4b5d73}.btn{display:inline-block;background:#f7bd18;color:#10284a;padding:14px 22px;border-radius:10px;font-weight:800;text-decoration:none;border:0;cursor:pointer}.btn.dark{background:#0d2b52;color:#fff}.visual{min-height:390px;border-radius:28px;background:radial-gradient(circle at 50% 25%,#ffc62b 0 15%,transparent 16%),linear-gradient(145deg,#163b69,#071b34);display:flex;align-items:end;justify-content:center;overflow:hidden;position:relative}.worker{width:220px;height:300px;border-radius:110px 110px 30px 30px;background:#12385f;position:relative;box-shadow:0 20px 30px #0004}.worker:before{content:'';position:absolute;width:100px;height:100px;background:#7a452d;border-radius:50%;left:60px;top:-45px;border:10px solid #ffc62b}.worker:after{content:'🔧';position:absolute;font-size:55px;right:-30px;top:80px}.cards{padding:55px 7%;display:grid;grid-template-columns:repeat(4,1fr);gap:18px}.card{background:#fff;padding:25px;border-radius:18px;box-shadow:0 8px 24px #1231}.card h3{margin-top:8px}.icon{font-size:35px}.wrap{max-width:900px;margin:45px auto;padding:0 20px}.form{background:#fff;padding:28px;border-radius:18px;box-shadow:0 8px 25px #1231}.form label{display:block;font-weight:700;margin:15px 0 6px}.form input,.form select,.form textarea{width:100%;padding:13px;border:1px solid #ccd5e0;border-radius:9px;font:inherit}.status{padding:15px;background:#eef5ff;border-left:5px solid #f5b900;margin-top:15px;border-radius:8px}footer{background:#0d2b52;color:#fff;padding:35px 7%;line-height:1.8;margin-top:40px}footer a{color:#ffc62b}.pros{padding:55px 7%;background:#eef4fb}.progrid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.small{color:#65758a}@media(max-width:800px){header{padding:0 4%;height:auto;min-height:65px;gap:10px}nav{display:none}.hero{grid-template-columns:1fr;padding:45px 5%}.visual{min-height:300px}.cards,.progrid{grid-template-columns:1fr 1fr;padding:35px 5%}}@media(max-width:520px){.cards,.progrid{grid-template-columns:1fr}h1{font-size:44px}}`;
app.get('/',(req,res)=>res.send(page(`<main><section class="hero"><div><p><b>🇬🇭 Proudly serving Ghana</b></p><h1>Need a job done?<br><span class="gold">Book a Pro.</span></h1><p class="lead">Get connected with a professional for electrical, CCTV & security, gate automation and generator services.</p><a class="btn" href="/book">Book a Service →</a> <a class="btn dark" href="/track">Track Booking</a></div><div class="visual"><div class="worker"></div></div></section><section><div class="cards"><div class="card"><div class="icon">⚡</div><h3>Electrical</h3><p>Wiring, repairs, lighting and power systems.</p></div><div class="card"><div class="icon">📹</div><h3>CCTV & Security</h3><p>CCTV, access control, electric fence and alarms.</p></div><div class="card"><div class="icon">🚪</div><h3>Gate Automation</h3><p>Automated gates, remote controls and intercoms.</p></div><div class="card"><div class="icon">🔋</div><h3>Generator & Power</h3><p>Installation, repairs and power support.</p></div></div></section><section class="pros"><div class="wrap"><h2>How it works</h2><ol><li>Tell us what you need.</li><li>We match you with a suitable professional.</li><li>The professional handles the job.</li><li>You confirm completion and leave a review.</li></ol></div></section></main>`,'Services by Dela | Ghana')));
app.get('/book',(req,res)=>res.send(page(`<div class="wrap"><h1>Book a <span class="gold">Service</span></h1><form class="form" method="post" action="/api/book"><label>Service</label><select name="service" required><option>Electrical Services</option><option>CCTV & Security</option><option>Gate Automation</option><option>Generator & Power</option><option>Other</option></select><label>Location</label><input name="location" placeholder="e.g. Lapaz, Accra" required><label>Describe the job</label><textarea name="description" rows="5" required></textarea><label>Urgency</label><select name="urgency"><option>Flexible</option><option>This week</option><option>Today</option><option>Emergency</option></select><label>Your name</label><input name="name" required><label>Phone / WhatsApp</label><input name="phone" required><br><br><button class="btn" type="submit">Submit Request →</button></form></div>`,'Book a Service | Services by Dela')));
app.post('/api/book',(req,res)=>{const d=load(),job={id:id(),createdAt:new Date().toISOString(),status:'NEW',...req.body};d.jobs.push(job);save(d);res.send(page(`<div class="wrap"><div class="form"><h1>Request received 🎉</h1><p class="lead">Your Job ID is:</p><h2>${job.id}</h2><div class="status">Keep this ID to track your booking. We will contact you using the number you provided.</div><br><a class="btn" href="/track?id=${job.id}">Track this booking</a></div></div>`,'Booking Confirmed | Services by Dela'))});
app.get('/track',(req,res)=>{let content=`<div class="wrap"><h1>Track your <span class="gold">Booking</span></h1><form class="form" method="get"><label>Job ID</label><input name="id" placeholder="SBD-2026-12345" value="${req.query.id||''}" required><br><br><button class="btn">Check Status</button></form>`;if(req.query.id){const j=load().jobs.find(x=>x.id===req.query.id);content+=j?`<div class="form" style="margin-top:20px"><h2>${j.service}</h2><p><b>Status:</b> ${j.status}</p><p><b>Location:</b> ${j.location}</p><p>${j.description}</p></div>`:`<div class="status">No booking found with that Job ID.</div>`}content+='</div>';res.send(page(content,'Track Booking | Services by Dela'))});
app.get('/support',(req,res)=>res.send(page(`<div class="wrap"><h1>We're here to <span class="gold">help.</span></h1><div class="cards" style="padding:20px 0"><div class="card"><h3>WhatsApp Support</h3><a class="btn" href="https://wa.me/233541721528">Chat on WhatsApp</a></div><div class="card"><h3>Call Support</h3><a class="btn" href="tel:0541721528">Call 0541721528</a></div></div><form class="form" method="post" action="/api/support"><label>Job ID (if applicable)</label><input name="jobId"><label>Your name</label><input name="name" required><label>Phone</label><input name="phone" required><label>How can we help?</label><textarea name="message" rows="5" required></textarea><br><br><button class="btn">Send Support Request</button></form></div>`,'Support | Services by Dela')));
app.post('/api/support',(req,res)=>{const d=load();d.tickets.push({id:'T-'+Date.now(),createdAt:new Date().toISOString(),status:'OPEN',...req.body});save(d);res.send(page(`<div class="wrap"><div class="form"><h1>Support request sent.</h1><p>We'll follow up using the contact details you provided.</p><a class="btn" href="/">Back home</a></div></div>`,'Support Request | Services by Dela'))});
app.get('/pro',(req,res)=>res.send(page(`<div class="wrap"><h1>Become a <span class="gold">Pro</span></h1><form class="form" method="post" action="/api/pro"><label>Full name</label><input name="name" required><label>Area</label><input name="area" required><label>Phone / WhatsApp</label><input name="phone" required><label>Services</label><textarea name="services" rows="4" required></textarea><label>Years of experience</label><input name="experience"><br><br><button class="btn">Apply to Join</button></form></div>`,'Become a Pro | Services by Dela')));
app.post('/api/pro',(req,res)=>{const d=load();d.pros.push({id:'P-'+Date.now(),createdAt:new Date().toISOString(),status:'PENDING',...req.body});save(d);res.send(page(`<div class="wrap"><div class="form"><h1>Application received.</h1><p>Thanks for applying to Services by Dela. Our team will contact you.</p></div></div>`,'Application Received | Services by Dela'))});
app.get('/admin',(req,res)=>{const token=req.query.key;if(token!==ADMIN_PASSWORD)return res.status(401).send(page(`<div class="wrap"><div class="form"><h1>Admin</h1><form><label>Password</label><input type="password" name="key"><br><br><button class="btn">Sign in</button></form></div></div>`));const d=load();res.send(page(`<div class="wrap"><h1>Admin <span class="gold">Dashboard</span></h1><div class="cards"><div class="card"><h2>${d.jobs.length}</h2><p>Jobs</p></div><div class="card"><h2>${d.pros.length}</h2><p>Pro applications</p></div><div class="card"><h2>${d.tickets.length}</h2><p>Support tickets</p></div></div><div class="form"><h2>Recent Jobs</h2>${d.jobs.slice(-20).reverse().map(j=>`<div class="status"><b>${j.id}</b> — ${j.service} — ${j.location} — <b>${j.status}</b></div>`).join('')||'<p>No jobs yet.</p>'}</div></div>`,'Admin | Services by Dela'))});
app.get('/api/health',(req,res)=>res.json({ok:true,service:'Services by Dela'}));
app.listen(PORT,()=>console.log('Services by Dela running on '+PORT));
